alter table tadminuser
    drop timezone_id,
    drop lost_login_status,
    drop acc_pwd_expires,
    drop password_salt,
    drop last_pwd_fail,
    drop bad_pwd_count,
    drop override_code,
    drop last_pwd_change,
    drop login_loc,
    drop login_time,
    drop position_id,
    drop logged_in,
    drop phone_switch,
    drop agent_id,
    drop email,
    drop status,
    drop login_uid;
