create procedure paudadminuser (
    p_aud_op like tadminuser_aud.aud_op,
    p_user_id_pre like tadminuser_aud.user_id default null,
    p_user_id_post like tadminuser_aud.user_id,
    p_username_pre like tadminuser_aud.username default null,
    p_username_post like tadminuser_aud.username,
    p_password_pre like tadminuser_aud.password default null,
    p_password_post like tadminuser_aud.password,
    p_fname_pre like tadminuser_aud.fname default null,
    p_fname_post like tadminuser_aud.fname,
    p_lname_pre like tadminuser_aud.lname default null,
    p_lname_post like tadminuser_aud.lname,
    p_login_uid_pre like tadminuser_aud.login_uid default null,
    p_login_uid_post like tadminuser_aud.login_uid,
    p_status_pre like tadminuser_aud.status default null,
    p_status_post like tadminuser_aud.status,
    p_email_pre like tadminuser_aud.email default null,
    p_email_post like tadminuser_aud.email,
    p_agent_id_pre like tadminuser_aud.agent_id default null,
    p_agent_id_post like tadminuser_aud.agent_id,
    p_phone_switch_pre like tadminuser_aud.phone_switch default null,
    p_phone_switch_post like tadminuser_aud.phone_switch,
    p_logged_in_pre like tadminuser_aud.logged_in default null,
    p_logged_in_post like tadminuser_aud.logged_in,
    p_position_id_pre like tadminuser_aud.position_id default null,
    p_position_id_post like tadminuser_aud.position_id,
    p_login_time_pre like tadminuser_aud.login_time default null,
    p_login_time_post like tadminuser_aud.login_time,
    p_login_loc_pre like tadminuser_aud.login_loc default null,
    p_login_loc_post like tadminuser_aud.login_loc,
    p_last_pwd_change_pre like tadminuser_aud.last_pwd_change default null,
    p_last_pwd_change_post like tadminuser_aud.last_pwd_change,
    p_override_code_pre like tadminuser_aud.override_code default null,
    p_override_code_post like tadminuser_aud.override_code,
    p_bad_pwd_count_pre like tadminuser_aud.bad_pwd_count default null,
    p_bad_pwd_count_post like tadminuser_aud.bad_pwd_count,
    p_last_pwd_fail_pre like tadminuser_aud.last_pwd_fail default null,
    p_last_pwd_fail_post like tadminuser_aud.last_pwd_fail,
    p_password_salt_pre like tadminuser_aud.password_salt default null,
    p_password_salt_post like tadminuser_aud.password_salt,
    p_acc_pwd_expires_pre like tadminuser_aud.acc_pwd_expires default null,
    p_acc_pwd_expires_post like tadminuser_aud.acc_pwd_expires,
    p_lost_login_status_pre like tadminuser_aud.lost_login_status default null,
    p_lost_login_status_post like tadminuser_aud.lost_login_status,
    p_timezone_id_pre like tadminuser_aud.timezone_id default null,
    p_timezone_id_post like tadminuser_aud.timezone_id
)
    define v_admin_id int;

    let v_admin_id = pSetGAdminUser();

    insert into tadminuser_aud (
        aud_id,
        aud_time,
        aud_op,
        user_id,
        username,
        password,
        fname,
        lname,
        login_uid,
        status,
        email,
        agent_id,
        phone_switch,
        logged_in,
        position_id,
        login_time,
        login_loc,
        last_pwd_change,
        override_code,
        bad_pwd_count,
        last_pwd_fail,
        password_salt,
        acc_pwd_expires,
        lost_login_status,
        timezone_id
    ) values (
        v_admin_id,
        CURRENT,
        p_aud_op,
        p_user_id_post,
        p_username_post,
        p_password_post,
        p_fname_post,
        p_lname_post,
        p_login_uid_post,
        p_status_post,
        p_email_post,
        p_agent_id_post,
        p_phone_switch_post,
        p_logged_in_post,
        p_position_id_post,
        p_login_time_post,
        p_login_loc_post,
        p_last_pwd_change_post,
        p_override_code_post,
        p_bad_pwd_count_post,
        p_last_pwd_fail_post,
        p_password_salt_post,
        p_acc_pwd_expires_post,
        p_lost_login_status_post,
        p_timezone_id_post
    );

end procedure;

--END
